swagger: '2.0'
info:
  version: '2016-06-10'
  x-release: v4
  title: Amazon Polly
  description: '<p>Amazon Polly is a web service that makes it easy to synthesize speech from text.</p> <p>The Amazon Polly service provides API operations for synthesizing high-quality speech from plain text and Speech Synthesis Markup Language (SSML), along with managing pronunciations lexicons that enable you to get the best results for your application domain.</p>'
  termsOfService: 'https://aws.amazon.com/service-terms/'
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: 'https://github.com/mermade/aws2openapi'
  license:
    name: Apache 2.0 License
    url: 'http://www.apache.org/licenses/'
  x-providerName: aws.amazon.com
  x-serviceName: polly
  x-origin:
    format: swagger
    version: '2.0'
    url: 'https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/polly-2016-06-10.normal.json'
    converter:
      url: 'https://github.com/mermade/aws2openapi'
      version: 1.0.0
      x-apisguru-direct: true
  x-apiClientRegistration:
    url: 'https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct'
  x-apisguru-categories:
    - cloud
  x-preferred: true
x-logo:
  url: 'https://media.amazonwebservices.com/blog/2007/big_pbaws_logo_300px.jpg'
  backgroundColor: '#FFFFFF'
externalDocs:
  description: Amazon Web Services documentation
  url: 'https://aws.amazon.com/polly/'
host: polly.amazonaws.com
basePath: /
x-hasEquivalentPaths: true
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
parameters:
  Action:
    name: Action
    in: header
    type: string
    required: true
  Version:
    name: Version
    in: header
    type: string
    required: true
  X-Amz-Content-Sha256:
    name: X-Amz-Content-Sha256
    in: header
    type: string
    required: false
  X-Amz-Date:
    name: X-Amz-Date
    in: header
    type: string
    required: false
  X-Amz-Algorithm:
    name: X-Amz-Algorithm
    in: header
    type: string
    required: false
  X-Amz-Credential:
    name: X-Amz-Credential
    in: header
    type: string
    required: false
  X-Amz-Security-Token:
    name: X-Amz-Security-Token
    in: header
    type: string
    required: false
  X-Amz-Signature:
    name: X-Amz-Signature
    in: header
    type: string
    required: false
  X-Amz-SignedHeaders:
    name: X-Amz-SignedHeaders
    in: header
    type: string
    required: false
securityDefinitions:
  hmac:
    type: apiKey
    name: Authorization
    in: header
    description: Amazon Signature authorization v4
    x-amazon-apigateway-authtype: awsSigv4
security:
  - hmac: []
paths:
  '/v1/lexicons/{LexiconName}':
    put:
      operationId: PutLexicon
      description: '<p>Stores a pronunciation lexicon in an AWS Region. If a lexicon with the same name already exists in the region, it is overwritten by the new lexicon. Lexicon operations have eventual consistency, therefore, it might take some time before the lexicon is available to the SynthesizeSpeech operation.</p> <p>For more information, see <a href="http://docs.aws.amazon.com/polly/latest/dg/managing-lexicons.html">Managing Lexicons</a>.</p>'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/PutLexiconOutput'
        '480':
          description: InvalidLexiconException
          schema:
            $ref: '#/definitions/InvalidLexiconException'
        '481':
          description: UnsupportedPlsAlphabetException
          schema:
            $ref: '#/definitions/UnsupportedPlsAlphabetException'
        '482':
          description: UnsupportedPlsLanguageException
          schema:
            $ref: '#/definitions/UnsupportedPlsLanguageException'
        '483':
          description: LexiconSizeExceededException
          schema:
            $ref: '#/definitions/LexiconSizeExceededException'
        '484':
          description: MaxLexemeLengthExceededException
          schema:
            $ref: '#/definitions/MaxLexemeLengthExceededException'
        '485':
          description: MaxLexiconsNumberExceededException
          schema:
            $ref: '#/definitions/MaxLexiconsNumberExceededException'
        '486':
          description: ServiceFailureException
          schema:
            $ref: '#/definitions/ServiceFailureException'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/PutLexiconInput'
        - name: LexiconName
          in: path
          type: string
          required: true
    parameters:
      - $ref: '#/parameters/Action'
      - $ref: '#/parameters/Version'
      - $ref: '#/parameters/X-Amz-Content-Sha256'
      - $ref: '#/parameters/X-Amz-Date'
      - $ref: '#/parameters/X-Amz-Algorithm'
      - $ref: '#/parameters/X-Amz-Credential'
      - $ref: '#/parameters/X-Amz-Security-Token'
      - $ref: '#/parameters/X-Amz-Signature'
      - $ref: '#/parameters/X-Amz-SignedHeaders'
  /v1/voices:
    get:
      operationId: DescribeVoices
      description: '<p>Returns the list of voices that are available for use when requesting speech synthesis. Each voice speaks a specified language, is either male or female, and is identified by an ID, which is the ASCII version of the voice name. </p> <p>When synthesizing speech ( <code>SynthesizeSpeech</code> ), you provide the voice ID for the voice you want from the list of voices returned by <code>DescribeVoices</code>.</p> <p>For example, you want your news reader application to read news in a specific language, but giving a user the option to choose the voice. Using the <code>DescribeVoices</code> operation you can provide the user with a list of available voices to select from.</p> <p> You can optionally specify a language code to filter the available voices. For example, if you specify <code>en-US</code>, the operation returns a list of all available US English voices. </p> <p>This operation requires permissions to perform the <code>polly:DescribeVoices</code> action.</p>'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/DescribeVoicesOutput'
        '480':
          description: InvalidNextTokenException
          schema:
            $ref: '#/definitions/InvalidNextTokenException'
        '481':
          description: ServiceFailureException
          schema:
            $ref: '#/definitions/ServiceFailureException'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/DescribeVoicesInput'
    parameters:
      - $ref: '#/parameters/Action'
      - $ref: '#/parameters/Version'
      - $ref: '#/parameters/X-Amz-Content-Sha256'
      - $ref: '#/parameters/X-Amz-Date'
      - $ref: '#/parameters/X-Amz-Algorithm'
      - $ref: '#/parameters/X-Amz-Credential'
      - $ref: '#/parameters/X-Amz-Security-Token'
      - $ref: '#/parameters/X-Amz-Signature'
      - $ref: '#/parameters/X-Amz-SignedHeaders'
  /v1/lexicons:
    get:
      operationId: ListLexicons
      description: 'Returns a list of pronunciation lexicons stored in an AWS Region. For more information, see <a href="http://docs.aws.amazon.com/polly/latest/dg/managing-lexicons.html">Managing Lexicons</a>.'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/ListLexiconsOutput'
        '480':
          description: InvalidNextTokenException
          schema:
            $ref: '#/definitions/InvalidNextTokenException'
        '481':
          description: ServiceFailureException
          schema:
            $ref: '#/definitions/ServiceFailureException'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/ListLexiconsInput'
    parameters:
      - $ref: '#/parameters/Action'
      - $ref: '#/parameters/Version'
      - $ref: '#/parameters/X-Amz-Content-Sha256'
      - $ref: '#/parameters/X-Amz-Date'
      - $ref: '#/parameters/X-Amz-Algorithm'
      - $ref: '#/parameters/X-Amz-Credential'
      - $ref: '#/parameters/X-Amz-Security-Token'
      - $ref: '#/parameters/X-Amz-Signature'
      - $ref: '#/parameters/X-Amz-SignedHeaders'
  /v1/speech:
    post:
      operationId: SynthesizeSpeech
      description: 'Synthesizes UTF-8 input, plain text or SSML, to a stream of bytes. SSML input must be valid, well-formed SSML. Some alphabets might not be available with all the voices (for example, Cyrillic might not be read at all by English voices) unless phoneme mapping is used. For more information, see <a href="http://docs.aws.amazon.com/polly/latest/dg/how-text-to-speech-works.html">How it Works</a>.'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/SynthesizeSpeechOutput'
        '480':
          description: TextLengthExceededException
          schema:
            $ref: '#/definitions/TextLengthExceededException'
        '481':
          description: InvalidSampleRateException
          schema:
            $ref: '#/definitions/InvalidSampleRateException'
        '482':
          description: InvalidSsmlException
          schema:
            $ref: '#/definitions/InvalidSsmlException'
        '483':
          description: LexiconNotFoundException
          schema:
            $ref: '#/definitions/LexiconNotFoundException'
        '484':
          description: ServiceFailureException
          schema:
            $ref: '#/definitions/ServiceFailureException'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/SynthesizeSpeechInput'
    parameters:
      - $ref: '#/parameters/Action'
      - $ref: '#/parameters/Version'
      - $ref: '#/parameters/X-Amz-Content-Sha256'
      - $ref: '#/parameters/X-Amz-Date'
      - $ref: '#/parameters/X-Amz-Algorithm'
      - $ref: '#/parameters/X-Amz-Credential'
      - $ref: '#/parameters/X-Amz-Security-Token'
      - $ref: '#/parameters/X-Amz-Signature'
      - $ref: '#/parameters/X-Amz-SignedHeaders'
definitions:
  Alphabet:
    type: string
  AudioStream:
    type: string
  ContentType:
    type: string
  DeleteLexiconInput:
    type: object
    example:
      Name: example
    properties: {}
  DeleteLexiconOutput:
    type: object
    example: {}
    properties: {}
  DescribeVoicesInput:
    type: object
    example:
      LanguageCode: en-GB
    properties: {}
  DescribeVoicesOutput:
    type: object
    example:
      Voices:
        - Gender: Female
          Id: Emma
          LanguageCode: en-GB
          LanguageName: British English
          Name: Emma
        - Gender: Male
          Id: Brian
          LanguageCode: en-GB
          LanguageName: British English
          Name: Brian
        - Gender: Female
          Id: Amy
          LanguageCode: en-GB
          LanguageName: British English
          Name: Amy
    properties:
      Voices:
        $ref: '#/definitions/VoiceList'
        description: A list of voices with their properties.
      NextToken:
        $ref: '#/definitions/NextToken'
        description: The pagination token to use in the next request to continue the listing of voices. <code>NextToken</code> is returned only if the response is truncated.
  ErrorMessage:
    type: string
  Gender:
    type: string
    enum:
      - Female
      - Male
  GetLexiconInput:
    type: object
    example:
      Name: ''
    properties: {}
  GetLexiconOutput:
    type: object
    example:
      Lexicon:
        Content: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n<lexicon version=\"1.0\" \r\n      xmlns=\"http://www.w3.org/2005/01/pronunciation-lexicon\"\r\n      xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" \r\n      xsi:schemaLocation=\"http://www.w3.org/2005/01/pronunciation-lexicon \r\n        http://www.w3.org/TR/2007/CR-pronunciation-lexicon-20071212/pls.xsd\"\r\n      alphabet=\"ipa\" \r\n      xml:lang=\"en-US\">\r\n  <lexeme>\r\n    <grapheme>W3C</grapheme>\r\n    <alias>World Wide Web Consortium</alias>\r\n  </lexeme>\r\n</lexicon>"
        Name: example
      LexiconAttributes:
        Alphabet: ipa
        LanguageCode: en-US
        LastModified: 1478542980.117
        LexemesCount: 1
        LexiconArn: 'arn:aws:polly:us-east-1:123456789012:lexicon/example'
        Size: 503
    properties:
      Lexicon:
        $ref: '#/definitions/Lexicon'
        description: 'Lexicon object that provides name and the string content of the lexicon. '
      LexiconAttributes:
        $ref: '#/definitions/LexiconAttributes'
        description: 'Metadata of the lexicon, including phonetic alphabetic used, language code, lexicon ARN, number of lexemes defined in the lexicon, and size of lexicon in bytes.'
  InvalidLexiconException:
    type: object
    properties:
      message:
        $ref: '#/definitions/ErrorMessage'
    description: 'Amazon Polly can''t find the specified lexicon. Verify that the lexicon''s name is spelled correctly, and then try again.'
  InvalidNextTokenException:
    type: object
    properties:
      message:
        $ref: '#/definitions/ErrorMessage'
    description: 'The NextToken is invalid. Verify that it''s spelled correctly, and then try again.'
  InvalidSampleRateException:
    type: object
    properties:
      message:
        $ref: '#/definitions/ErrorMessage'
    description: The specified sample rate is not valid.
  InvalidSsmlException:
    type: object
    properties:
      message:
        $ref: '#/definitions/ErrorMessage'
    description: 'The SSML you provided is invalid. Verify the SSML syntax, spelling of tags and values, and then try again.'
  LanguageCode:
    type: string
    enum:
      - cy-GB
      - da-DK
      - de-DE
      - en-AU
      - en-GB
      - en-GB-WLS
      - en-IN
      - en-US
      - es-ES
      - es-US
      - fr-CA
      - fr-FR
      - is-IS
      - it-IT
      - ja-JP
      - nb-NO
      - nl-NL
      - pl-PL
      - pt-BR
      - pt-PT
      - ro-RO
      - ru-RU
      - sv-SE
      - tr-TR
  LanguageName:
    type: string
  LastModified:
    type: string
    format: date-time
  LexemesCount:
    type: integer
  Lexicon:
    type: object
    properties:
      Content:
        $ref: '#/definitions/LexiconContent'
        description: Lexicon content in string format. The content of a lexicon must be in PLS format.
      Name:
        $ref: '#/definitions/LexiconName'
        description: Name of the lexicon.
    description: 'Provides lexicon name and lexicon content in string format. For more information, see <a href="https://www.w3.org/TR/pronunciation-lexicon/">Pronunciation Lexicon Specification (PLS) Version 1.0</a>.'
  LexiconArn:
    type: string
  LexiconAttributes:
    type: object
    properties:
      Alphabet:
        $ref: '#/definitions/Alphabet'
        description: Phonetic alphabet used in the lexicon. Valid values are <code>ipa</code> and <code>x-sampa</code>.
      LanguageCode:
        $ref: '#/definitions/LanguageCode'
        description: 'Language code that the lexicon applies to. A lexicon with a language code such as "en" would be applied to all English languages (en-GB, en-US, en-AUS, en-WLS, and so on.'
      LastModified:
        $ref: '#/definitions/LastModified'
        description: Date lexicon was last modified (a timestamp value).
      LexiconArn:
        $ref: '#/definitions/LexiconArn'
        description: Amazon Resource Name (ARN) of the lexicon.
      LexemesCount:
        $ref: '#/definitions/LexemesCount'
        description: Number of lexemes in the lexicon.
      Size:
        $ref: '#/definitions/Size'
        description: 'Total size of the lexicon, in characters.'
    description: 'Contains metadata describing the lexicon such as the number of lexemes, language code, and so on. For more information, see <a href="http://docs.aws.amazon.com/polly/latest/dg/managing-lexicons.html">Managing Lexicons</a>.'
  LexiconContent:
    type: string
  LexiconDescription:
    type: object
    properties:
      Name:
        $ref: '#/definitions/LexiconName'
        description: Name of the lexicon.
      Attributes:
        $ref: '#/definitions/LexiconAttributes'
        description: Provides lexicon metadata.
    description: Describes the content of the lexicon.
  LexiconDescriptionList:
    type: array
    items:
      $ref: '#/definitions/LexiconDescription'
  LexiconName:
    type: string
    pattern: '[0-9A-Za-z]{1,20}'
    format: password
  LexiconNameList:
    type: array
    items:
      $ref: '#/definitions/LexiconName'
    maxItems: 5
  LexiconNotFoundException:
    type: object
    properties:
      message:
        $ref: '#/definitions/ErrorMessage'
    description: '<p>Amazon Polly can''t find the specified lexicon. This could be caused by a lexicon that is missing, its name is misspelled or specifying a lexicon that is in a different region.</p> <p>Verify that the lexicon exists, is in the region (see <a>ListLexicons</a>) and that you spelled its name is spelled correctly. Then try again.</p>'
  LexiconSizeExceededException:
    type: object
    properties:
      message:
        $ref: '#/definitions/ErrorMessage'
    description: The maximum size of the specified lexicon would be exceeded by this operation.
  ListLexiconsInput:
    type: object
    example: {}
    properties: {}
  ListLexiconsOutput:
    type: object
    example:
      Lexicons:
        - Attributes:
            Alphabet: ipa
            LanguageCode: en-US
            LastModified: 1478542980.117
            LexemesCount: 1
            LexiconArn: 'arn:aws:polly:us-east-1:123456789012:lexicon/example'
            Size: 503
          Name: example
    properties:
      Lexicons:
        $ref: '#/definitions/LexiconDescriptionList'
        description: A list of lexicon names and attributes.
      NextToken:
        $ref: '#/definitions/NextToken'
        description: The pagination token to use in the next request to continue the listing of lexicons. <code>NextToken</code> is returned only if the response is truncated.
  MaxLexemeLengthExceededException:
    type: object
    properties:
      message:
        $ref: '#/definitions/ErrorMessage'
    description: The maximum size of the lexeme would be exceeded by this operation.
  MaxLexiconsNumberExceededException:
    type: object
    properties:
      message:
        $ref: '#/definitions/ErrorMessage'
    description: The maximum number of lexicons would be exceeded by this operation.
  NextToken:
    type: string
  OutputFormat:
    type: string
    enum:
      - mp3
      - ogg_vorbis
      - pcm
  PutLexiconInput:
    type: object
    required:
      - Content
    example:
      Content: 'file://example.pls'
      Name: W3C
    properties:
      Content:
        $ref: '#/definitions/LexiconContent'
        description: Content of the PLS lexicon as string data.
  PutLexiconOutput:
    type: object
    example: {}
    properties: {}
  RequestCharacters:
    type: integer
  SampleRate:
    type: string
  ServiceFailureException:
    type: object
    properties:
      message:
        $ref: '#/definitions/ErrorMessage'
    description: An unknown condition has caused a service failure.
  Size:
    type: integer
  SynthesizeSpeechInput:
    type: object
    required:
      - OutputFormat
      - Text
      - VoiceId
    example:
      LexiconNames:
        - example
      OutputFormat: mp3
      SampleRate: '8000'
      Text: All Gaul is divided into three parts
      TextType: text
      VoiceId: Joanna
    properties:
      LexiconNames:
        $ref: '#/definitions/LexiconNameList'
        description: 'List of one or more pronunciation lexicon names you want the service to apply during synthesis. Lexicons are applied only if the language of the lexicon is the same as the language of the voice. For information about storing lexicons, see <a href="http://docs.aws.amazon.com/polly/latest/dg/API_PutLexicon.html">PutLexicon</a>.'
      OutputFormat:
        $ref: '#/definitions/OutputFormat'
        description: ' The audio format in which the resulting stream will be encoded. '
      SampleRate:
        $ref: '#/definitions/SampleRate'
        description: '<p> The audio frequency specified in Hz. </p> <p>The valid values for <code>mp3</code> and <code>ogg_vorbis</code> are "8000", "16000", and "22050". The default value is "22050". </p> <p> Valid values for <code>pcm</code> are "8000" and "16000" The default value is "16000". </p>'
      Text:
        $ref: '#/definitions/Text'
        description: ' Input text to synthesize. If you specify <code>ssml</code> as the <code>TextType</code>, follow the SSML format for the input text. '
      TextType:
        $ref: '#/definitions/TextType'
        description: ' Specifies whether the input text is plain text or SSML. The default value is plain text. For more information, see <a href="http://docs.aws.amazon.com/polly/latest/dg/ssml.html">Using SSML</a>.'
      VoiceId:
        $ref: '#/definitions/VoiceId'
        description: ' Voice ID to use for the synthesis. You can get a list of available voice IDs by calling the <a href="http://docs.aws.amazon.com/polly/latest/dg/API_DescribeVoices.html">DescribeVoices</a> operation. '
  SynthesizeSpeechOutput:
    type: object
    example:
      AudioStream: TEXT
      ContentType: audio/mpeg
      RequestCharacters: 37
    properties:
      AudioStream:
        $ref: '#/definitions/AudioStream'
        description: ' Stream containing the synthesized speech. '
  Text:
    type: string
  TextLengthExceededException:
    type: object
    properties:
      message:
        $ref: '#/definitions/ErrorMessage'
    description: 'The value of the "Text" parameter is longer than the accepted limits. The limit for input text is a maximum of 3000 characters total, of which no more than 1500 can be billed characters. SSML tags are not counted as billed characters.'
  TextType:
    type: string
    enum:
      - ssml
      - text
  UnsupportedPlsAlphabetException:
    type: object
    properties:
      message:
        $ref: '#/definitions/ErrorMessage'
    description: The alphabet specified by the lexicon is not a supported alphabet. Valid values are <code>x-sampa</code> and <code>ipa</code>.
  UnsupportedPlsLanguageException:
    type: object
    properties:
      message:
        $ref: '#/definitions/ErrorMessage'
    description: 'The language specified in the lexicon is unsupported. For a list of supported languages, see <a href="http://docs.aws.amazon.com/polly/latest/dg/API_LexiconAttributes.html">Lexicon Attributes</a>.'
  Voice:
    type: object
    properties:
      Gender:
        $ref: '#/definitions/Gender'
        description: Gender of the voice.
      Id:
        $ref: '#/definitions/VoiceId'
        description: Amazon Polly assigned voice ID. This is the ID that you specify when calling the <code>SynthesizeSpeech</code> operation.
      LanguageCode:
        $ref: '#/definitions/LanguageCode'
        description: Language code of the voice.
      LanguageName:
        $ref: '#/definitions/LanguageName'
        description: Human readable name of the language in English.
      Name:
        $ref: '#/definitions/VoiceName'
        description: 'Name of the voice (for example, Salli, Kendra, etc.). This provides a human readable voice name that you might display in your application.'
    description: Description of the voice.
  VoiceId:
    type: string
    enum:
      - Geraint
      - Gwyneth
      - Mads
      - Naja
      - Hans
      - Marlene
      - Nicole
      - Russell
      - Amy
      - Brian
      - Emma
      - Raveena
      - Ivy
      - Joanna
      - Joey
      - Justin
      - Kendra
      - Kimberly
      - Salli
      - Conchita
      - Enrique
      - Miguel
      - Penelope
      - Chantal
      - Celine
      - Mathieu
      - Dora
      - Karl
      - Carla
      - Giorgio
      - Mizuki
      - Liv
      - Lotte
      - Ruben
      - Ewa
      - Jacek
      - Jan
      - Maja
      - Ricardo
      - Vitoria
      - Cristiano
      - Ines
      - Carmen
      - Maxim
      - Tatyana
      - Astrid
      - Filiz
  VoiceList:
    type: array
    items:
      $ref: '#/definitions/Voice'
  VoiceName:
    type: string
